server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: dev
        password: 123
        namespace: 1d35246f-5a5b-493c-9373-86a840d67305

management:
  endpoints:
    web:
      exposure:
        include: "*"
