server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wqif/springcloud-config.git
          search-paths:
            - springcloud-config
          skipSslValidation: true # 跳过ssl认证
          timeout: 15
      label: main

eureka:
  client:
    register-with-eureka: true # 表示向注册中心注册自己 默认为true
    fetch-registry: true # 是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/