server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456

  cloud:
    stream:
      bindings: # 服务的整合处理
        send-out-0: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设为text/plain
          binder: rabbit
      function:
        definition: send


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的间隔时间，默认30
    lease-expiration-duration-in-seconds: 5 # 超过5秒间隔，默认90
    instance-id: send-8801.com # 主机名
    prefer-ip-address: true # 显示ip
