version: '3.2'
services:
  zk:
    restart: always
    image: zookeeper:3.6.2
    container_name: zookeeper
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data
      - ./datalog:/datalog
      - ./logs:/logs
    ports:
      - 2181:2181


