server:
  port: 8401

spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 1d35246f-5a5b-493c-9373-86a840d67305
        username: dev
        password: 123
    sentinel:
      transport:
        dashboard: localhost:8090 # 配置sentinel dashboard地址
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: "*"