server:
  port: 10083

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 入驻地址
feign:
  client:
    config:
      default:
        connect-timeout: 5000 # 设置请求连接超时时间10s，默认为一直阻塞
        read-timeout: 5000 # 设置请求处理超时时间5s，默认为一直阻塞
