version: '3.2'
services:
  seata-server:
    image: seataio/seata-server:1.4.2
    restart: always
    ports:
      - 8091:8091
    container_name: seata-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/:/seata-server/config
    environment:
      - SEATA_CONFIG_NAME=file:/seata-server/config/registry
